In [62]:
# import library
import numpy as np
import pandas as pd
from sklearn import tree

In [63]:
# membaca dataset
ukaiDataset = pd.read_excel('DatasetUKAI.xlsx', header=0) 

In [64]:
ukaiDataset.head()

No  NOMOR PESERTA        INSTITUSI             NAMA LENGKAP        NILAI  \
0   1   210333301546  PESERTA MANDIRI           ALl SYAHBUDDlN  DlBAWAH NBL   
1   2   210333302485  PESERTA MANDIRI  MUHAMMAD HANlEP PERMANA  DlBAWAH NBL   
2   3   210333302688  PESERTA MANDIRI               RlDWANSYAH  DlBAWAH NBL   
3   4   210333303995  PESERTA MANDIRI         ANGGA SUHERDlANA  DlBAWAH NBL   
4   5   210333304551  PESERTA MANDIRI     DlAS AGl LlA ARDlANA  DlBAWAH NBL   

    KESIMPULAN  
0  Tidak Lulus  
1  Tidak Lulus  
2  Tidak Lulus  
3  Tidak Lulus  
4  Tidak Lulus

In [65]:
# mengubah kelas (kolom) dari string ke unique-Integer
ukaiDataset["KESIMPULAN"] = pd.factorize(ukaiDataset.KESIMPULAN)[0]

In [66]:
# mengubah kelas (INSTITUSI) dari string ke unique-Integer
ukaiDataset["INSTITUSI"] = pd.factorize(ukaiDataset.INSTITUSI)[0]

In [67]:
# mengubah kelas (NILAI) dari string ke unique-Integer
ukaiDataset["NILAI"] = pd.factorize(ukaiDataset.NILAI)[0]

In [68]:
ukaiDataset.head()

No  NOMOR PESERTA  INSTITUSI             NAMA LENGKAP  NILAI  KESIMPULAN
0   1   210333301546          0           ALl SYAHBUDDlN      0           0
1   2   210333302485          0  MUHAMMAD HANlEP PERMANA      0           0
2   3   210333302688          0               RlDWANSYAH      0           0
3   4   210333303995          0         ANGGA SUHERDlANA      0           0
4   5   210333304551          0     DlAS AGl LlA ARDlANA      0           0

In [69]:
print(ukaiDataset)

      No  NOMOR PESERTA  INSTITUSI              NAMA LENGKAP  NILAI  \
0      1   210333301546          0            ALl SYAHBUDDlN      0   
1      2   210333302485          0   MUHAMMAD HANlEP PERMANA      0   
2      3   210333302688          0                RlDWANSYAH      0   
3      4   210333303995          0          ANGGA SUHERDlANA      0   
4      5   210333304551          0      DlAS AGl LlA ARDlANA      0   
..   ...            ...        ...                       ...    ...   
317  318   210501904845          1       SHlNTA DAMA APRYANl      1   
318  319   210501904846          1       MUHAMMAD SYAMSUDDlN      0   
319  320   210501904848          1           SONTA TUMANGGOR      0   
320  321   210501904850          1              llS PRlYANTl      0   
321  322   210501904880          1  FRANSlSKA VlTA HANDAYANl      0   

     KESIMPULAN  
0             0  
1             0  
2             0  
3             0  
4             0  
..          ...  
317           1  
318

In [70]:
# menghapus kolom "NOMOR PESERTA" & "NAMA LENGKAP"
ukaiDataset = ukaiDataset.drop(labels="NOMOR PESERTA", axis=1)
ukaiDataset = ukaiDataset.drop(labels="NAMA LENGKAP", axis=1)

In [71]:
print(ukaiDataset)

      No  INSTITUSI  NILAI  KESIMPULAN
0      1          0      0           0
1      2          0      0           0
2      3          0      0           0
3      4          0      0           0
4      5          0      0           0
..   ...        ...    ...         ...
317  318          1      1           1
318  319          1      0           0
319  320          1      0           0
320  321          1      0           0
321  322          1      0           0

[322 rows x 4 columns]


In [72]:
# mengubah dataframe ke array numpy
ukaiDataset = ukaiDataset.to_numpy()

In [73]:
print(ukaiDataset)

[[  1   0   0   0]
 [  2   0   0   0]
 [  3   0   0   0]
 ...
 [320   1   0   0]
 [321   1   0   0]
 [322   1   0   0]]


In [74]:
# membagi dataset 250 untuk training dan 72 untuk testing
dataTraining = np.concatenate((ukaiDataset[0:200, :], ukaiDataset[250:300, :]), axis=0)
dataTesting = np.concatenate((ukaiDataset[200:250, :], ukaiDataset[300:322, :]), axis=0)

In [75]:
print(dataTraining)
len(dataTraining)

[[  1   0   0   0]
 [  2   0   0   0]
 [  3   0   0   0]
 [  4   0   0   0]
 [  5   0   0   0]
 [  6   0   0   0]
 [  7   0   0   0]
 [  8   0   0   0]
 [  9   0   0   0]
 [ 10   0   0   0]
 [ 11   1   0   0]
 [ 12   1   0   0]
 [ 13   1   1   1]
 [ 14   1   0   0]
 [ 15   1   0   0]
 [ 16   1   1   1]
 [ 17   1   1   1]
 [ 18   1   1   1]
 [ 19   1   0   0]
 [ 20   1   1   1]
 [ 21   1   1   1]
 [ 22   1   0   0]
 [ 23   1   0   0]
 [ 24   1   1   1]
 [ 25   1   0   0]
 [ 26   1   1   1]
 [ 27   1   1   1]
 [ 28   1   1   1]
 [ 29   1   0   0]
 [ 30   1   1   1]
 [ 31   1   0   0]
 [ 32   1   0   0]
 [ 33   1   0   0]
 [ 34   1   1   1]
 [ 35   1   0   0]
 [ 36   1   1   1]
 [ 37   1   0   0]
 [ 38   1   1   1]
 [ 39   1   1   1]
 [ 40   1   1   1]
 [ 41   1   0   0]
 [ 42   1   1   1]
 [ 43   1   1   1]
 [ 44   1   1   1]
 [ 45   1   0   0]
 [ 46   1   1   1]
 [ 47   1   1   1]
 [ 48   1   1   1]
 [ 49   1   1   1]
 [ 50   1   1   1]
 [ 51   1   0   0]
 [ 52   1   1   1]
 [ 53   1   

250

In [77]:
# memecah dataset ke input dan label
inputTraining = dataTraining[:, 0:3]
inputTesting = dataTesting[:, 0:3]
labelTraining = dataTraining[:, 3]
labelTesting = dataTesting[:, 3]
print(labelTesting)
len(labelTesting)

[1 1 0 0 0 0 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 1 1
 0 0 0 1 0 0 0 1 1 0 1 0 0 1 0 1 1 0 1 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0]


72

In [78]:
# mendefinisikan decision tree classifier
model = tree.DecisionTreeClassifier()

In [79]:
# mentraining model
model = model.fit(inputTraining, labelTraining)

In [80]:
# memprediksi input data testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [1 1 0 0 0 0 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 1 1
 0 0 0 1 0 0 0 1 1 0 1 0 0 1 0 1 1 0 1 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0]
Hasil Prediksi :  [1 1 0 0 0 0 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 1 1
 0 0 0 1 0 0 0 1 1 0 1 0 0 1 0 1 1 0 1 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0]


In [81]:
# menghitung akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, " data")
print("Prediksi Salah :", prediksiSalah, " data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, " %")

Prediksi Benar : 72  data
Prediksi Salah : 0  data
Akurasi : 100.0  %


In [85]:
import pydotplus
from sklearn import tree
dot_data = tree.export_graphviz(model, out_file=None)
from IPython.display import Image
graph = pydotplus.graph_from_dot_data(dot_data)
Image(graph.create_png())
graph.write_png('ukai.png')

True